# This workflow will upload a Python Package for netunicorn-connector using Twine when pyproject.toml is modified

name: Release

on:
## uncomment this when you are ready to publish to PyPI
#  push:
#    paths:
#      - "pyproject.toml"
#    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      local_version_is_higher: ${{ steps.check-pypi-version.outputs.local_version_is_higher }}

    steps:
      - uses: actions/checkout@v3
      - name: Check if local version newer than PyPI version
        id: check-pypi-version
        uses: maybe-hello-world/pyproject-check-version@v3

  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    needs: check-version
    if: ${{ needs.check-version.outputs.local_version_is_higher == 'true' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
